### ISSUE TITLE
Does not login again

### ISSUE THREAD

**Issue by atd** [P2Pvalue/angular-swellrt#10]
After several days of using the app, angular-swellrt is not able to login again:

SwellRT logs the following:

```
     [java] jun 15, 2015 12:54:40 PM org.waveprotocol.box.server.rpc.AuthenticationServlet doPost
     [java] INFORMACIÓN: Authenticated user test@local.net
     [java] jun 15, 2015 12:54:41 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$WebSocketConnection <init>
     [java] INFORMACIÓN: New websocket connection set up for user null
     [java] jun 15, 2015 12:54:41 PM org.waveprotocol.box.server.frontend.ClientFrontendImpl openRequest
     [java] INFORMACIÓN: received openRequest from null for [WaveId local.net/gen+12345abcde], filter IdFilter[prefixes=[swl, user+test@local.net, conv]], known wavelets: []
     [java] jun 15, 2015 12:54:41 PM org.waveprotocol.box.server.frontend.WaveClientRpcImpl$1 onFailure
     [java] ADVERTENCIA: openRequest failure: Not logged in
     [java] jun 15, 2015 12:54:41 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$Connection$1 run
     [java] INFORMACIÓN: error = Not logged in

```

Loging in manually in SwellRT seems to fix the problem.

**Comment by pablojan** [comment]
That is quite odd. I would check if cookie WSESSIONID is properly sent in
each request after login.

2015-06-15 13:41 GMT+02:00 Antonio Tapiador notifications@github.com:

**Comment by atd** [comment]
Thank you @pablojan 

More accurate:

Browser:

``` javascript
SwellRT.startSession(window.swellrtConfig.server, window.swellrtConfig.user, window.swellrtConfig.pass);
true
```

SwellRT

```
     [java] jun 15, 2015 1:46:28 PM org.waveprotocol.box.server.rpc.AuthenticationServlet doPost
     [java] INFORMACIÓN: Authenticated user test@local.net
     [java] jun 15, 2015 1:46:28 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$WebSocketConnection <init>
     [java] INFORMACIÓN: New websocket connection set up for user null
```

**Comment by atd** [comment]
The requests:

```
POST /auth/signin?r=none HTTP/1.1
Host: 192.168.1.112:9898
Connection: keep-alive
Content-Length: 36
Origin: http://127.0.0.1:9001
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: http://127.0.0.1:9001/index.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://127.0.0.1:9001
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: 
Set-Cookie: WSESSIONID=10r9w1qe3fg8ifc2hj5xpe959;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/plain; charset=ISO-8859-1
Content-Length: 17
Server: Jetty(9.1.1.v20140108)

GET ws://192.168.1.112:9898/socket HTTP/1.1
Host: 192.168.1.112:9898
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://127.0.0.1:9001
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Sec-WebSocket-Key: HcQneKCyE38uJPXUT0m5JA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: GyM03hWxS9lq6RbBgoQmP1lRpwA=
Sec-WebSocket-Extensions: permessage-deflate

```

**Comment by pablojan** [comment]
In that GET request I can't see the Cookie header for WSESSIONID.
In addition, the header Origin: http://127.0.0.1:9001 shouldn't be a IP or
host name for the loopback (neither localhost nor 127.0.0.1 ). CORS doesn't
work well with them.
In my local environment I set other hostnames in /etc/hosts

Following the response for the login request and the request of the
WebSocket upgrade. In the latter you can see the WSESSIONID Cookie header

Hope it helps!

POST response
Host: wave.p2pvalue.eu
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101
Firefox/36.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://showcase.net:9009/
Content-Length: 46
Origin: http://showcase.net:9009
Cookie: WSESSIONID=ba21kcp9dyzvy9zv29ruypup
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

GET request
Host: wave.p2pvalue.eu
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101
Firefox/36.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://showcase.net:9009
Sec-WebSocket-Key: 04Xxc1Qg+7ixPS8RH1gy6Q==
Cookie: WSESSIONID=13p6mu7pziu6812osclx5lnh1i
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

2015-06-15 13:50 GMT+02:00 Antonio Tapiador notifications@github.com:

**Comment by atd** [comment]
You are totally right. It is a CORS issue. Changing `127.0.0.1` with `192.168.1.x` solves the problem and now the socket request includes the cookie header.

Thank you!
