### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/angular-swellrt#20]
``` js
community.image = new swellRT.FileObject(undefined);
```

and

``` js
community.image = undefined;
```

should delete the file in the server.

Instead, they leave the file unchanged.

(Please, consider the two ways to delete a file I propose to avoid ugly checks in front-end.)

**Comment by pablojan** [comment]
Sure, you should have been read the documentation

El 11/3/2016 7:15, David Llop notifications@github.com escribió:

community.image = new swellRT.FileObject(undefined);

and

community.image = undefined;

should delete the file in the server.

Instead, they leave the file unchanged.

(Please, consider the two ways to delete a file I propose to avoid ugly checks in front-end.)

**Comment by atfornes** [comment]
@pablojan, I do not understand your message:
- is there a way to erase attachements in SwellRT?
- is it explained in the Wiki?

thanks! :smile:

**Comment by pablojan** [comment]
Sorry, I thought I've added that to the wiki.
In a SwellRT's File object you can use the method clearValue(). It will
delete the file from the server async but the method will return
inmediatly, not need to set a callback.
Also, the file will be delete if you remove the File object from its
parent, via <list>.remove(<index>) or <map>.remove(<key>).

2016-03-11 11:29 GMT+01:00 atfornes notifications@github.com:

**Comment by atfornes** [comment]
I am currently working on this, `delete community.image` should work now, I will fix it so `comunity.image = undefined` and `comunity.image = new FileObject(undefined)` erase also the file.

**Comment by atd** [comment]
Awesome @atfornes ! Syntactic sugar for everyone!

**Comment by atfornes** [comment]
@llopv, now `comunity.image = undefined` and `comunity.image = new FileObject(undefined)` erase also the file.

Please avoid when possible assigning undefined to properties of the object, as I just explained in the documentation, it might result in unexpected behaviour. `delete comunity.image` and `comunity.image = new FileObject(undefined)` are safe to use :smile:

**Comment by atfornes** [comment]
@llopv, be also careful with https://github.com/P2Pvalue/swellrt/issues/129 when using `comunity.image = new FileObject(undefined)`, until it is fixed, the url of the image will still point to the erased file, resulting in an error and a ugly missing image image.
