### ISSUE TITLE
Tons of activity in websockers

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/angular-swellrt#22]
In staging's [Testing teem project](https://staging.teem.works/#/teems/cHJvdG90eXBlLnAycHZhbHVlLmV1L3MrWExFcVdIT2JUaUE?tab=chat) there is a lot of websocket activity when two users are connected.

**Comment by atfornes** [comment]
Thanks @llopv for reporting, please, feel free to provide as many information as possible to reproduce the issue and to visualize the symptoms of the problem.

**Comment by atd** [comment]
Further info:
1. Open [this Teem](https://staging.teem.works/#/teems/cHJvdG90eXBlLnAycHZhbHVlLmV1L3MrWExFcVdIT2JUaUE?tab=pad) and the developer tools. You will see the `Atmosphere callback 200` message going crazy
2. Open the network tab in the developer console and select `WS`
3. In the `Frames` tab you can see the messages from the wave protocol. You can get info about what is going on expanding them

![image](https://cloud.githubusercontent.com/assets/26228/15111017/b29a2d94-15e4-11e6-83cb-eab7ec6c654d.png)

**Comment by atfornes** [comment]
thanks @atd!

**Comment by atd** [comment]
I seemed to stop when I closed another tab with the same teem, so maybe it is related with opening several tabs ¿?

**Comment by llopv** [comment]
I observed it happens with two different users in the same wave.

**Comment by atfornes** [comment]
See also https://github.com/P2Pvalue/swellrt/issues/161
